version: "3.9"
services:
  gatus:
    image: twinproduction/gatus:latest
    restart: always
    ports:
      - "8081:8080"
    environment:
      - POSTGRES_USER=gatus_uptime_user # postgres user with access to the database
      - POSTGRES_PASSWORD=gatuspassword # postgres user password
      - POSTGRES_DB=gatus_uptime # this should be the name of your postgres database
    volumes:
      - ./config:/config
