version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: 0:0
    ports:
      - 8081:80
    volumes:
      - /root/docker/filebrowser/share:/srv
      - /root/docker/filebrowser/database/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true