storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@192.168.1.153:5432/${POSTGRES_DB}?sslmode=disable"

endpoint-defaults: &defaults
  group: External
  interval: 30s
  client:
    timeout: 10s
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 48h"

endpoints:
  - name: divemagazinetr.com - HTTP
    <<: *defaults
    url: "https://divemagazinetr.com"

  - name: divemagazinetr.com - DNS
    group: External
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "divemagazinetr.com"
      query-type: "A"
    conditions:
      - "[BODY] == 173.201.191.4"
      - "[DNS_RCODE] == NOERROR"

  - name: divemagazinetr.com - Ping
    group: External
    url: "icmp://divemagazinetr.com"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Postgres
    group: Internal
    url: "tcp://192.168.1.153:5432"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"